### ISSUE TITLE
Add multi-string support for variable values

### ISSUE THREAD

**Issue by air3ijai** [druzsan/setup-matrix#5]
We are trying to check how to use that action with `include` and it fails with our case (`shell: bash -e`), which is expected as described in the documentation
> There is currently no way to pass multiline strings or strings containing colons and/or commas as variable names or values. If you need to have such strings please open an issue.

```yaml
name: Matrix
on:
  push:
  workflow_dispatch:

jobs:
  # Setup matrix
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
    steps:
      - id: setup-matrix
        uses: druzsan/setup-matrix@v1
        with:
          include: |
            os: linux cpu: amd64 run-on: ubuntu-latest shell: bash -e,
            os: macos cpu: amd64 run-on: macos-latest shell: bash -e,
            os: windows cpu: amd64 run-on: windows-latest shell: msys2

  # Setup python and print version
  build:
    needs: setup-matrix
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.run-on }}
    name: '${{ matrix.os }}-${{ matrix.cpu }}-${{ matrix.shell }}'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
```

**Comment by druzsan** [comment]
Hi @air3ijai, I can confirm this feature is not working at the moment and I couldn't bypass it myself.

Furthermore, it works with plain GitHub strategy matrices, so it seems reasonable for me to implement.

So I am starting to implement this feature.

**Comment by druzsan** [comment]
Hi @air3ijai

**Update:** I rewrote the action with Python and it seems to work for virtually any case (special characters/spaces/multilines in both variable name and values) now.

Here is your [workflow](https://github.com/druzsan/setup-matrix/blob/feature/use-python-dockerfile/.github/workflows/issue-5.yml) using the new version and its corresponding [run](https://github.com/druzsan/setup-matrix/actions/runs/7811429347).

**Breaking Changes:** since had to parse many edge cases I stepped back from my "own" format to classic YAML as a string. Flow and non-flow YAML syntaxes are both supported. Basically, if you had
```yaml
strategy:
  matrix:
    variable1: [value1, value2]
    variable2: [value1, value2]
    include:
      - variable1: value3
      - variable2: value3 variable3: value1
    exclude:
      - variable1: value1 variable2: value2
```
now just copy-paste it to the actions inputs:
```yaml
steps:
  - uses: druzsan/setup-matrix@feature/use-python-dockerfile
    with:
      matrix: |
        variable1: [value1, value2]
        variable2: [value1, value2]
      include: |
        - variable1: value3
        - variable2: value3 variable3: value1
      exclude: |
        - variable1: value1 variable2: value2
```

**WIP:** the feature is not released yet, I need some more time to test it out. So you can use the branch specified (`uses: druzsan/setup-matrix@feature/use-python-dockerfile`) to test it yourself if you wish, but do not fully rely on the unreleased state.
